# dataset configs
train_data_path: ./data/CREATIS/
test_data_path: ./data/DIRLAB/mha/
patch_size: 64
overlap_size: 8
train_cases: [0, 1, 2, 3, 4]
val_cases: [5]
test_cases: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# dataloader configs
data_loader:
  batch_size: 24
  shuffle: True
  num_workers: 1

# training settings
n_epochs: 30
lr: 0.0001
momentum: 0.99
save_every: 1

# criterion settings
window_size : 9
lamda: 0.05
mu1: 1
mu2: 0.5

# save directories
save_dir: ./saved_ours/